// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6e762f9e-3a0e-4624-92fe-4fb16e0a65a9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBatbangcuchiChange();
void onStateChange();

float batbangcuchi;
float current;
CloudSmartPlug state;
int power;
int voltage;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(batbangcuchi, READWRITE, ON_CHANGE, onBatbangcuchiChange);
  ArduinoCloud.addProperty(current, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(state, READWRITE, ON_CHANGE, onStateChange);
  ArduinoCloud.addProperty(power, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltage, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
